### PR TITLE
chore: README structure and common sections

### PR DESCRIPTION
**Pull request by peppelinux**

### CODE REVIEW

**Review by rohe — APPROVED** [review]
Actually I like the sentence:
Implementation of everything OIDC and OAuth2.
But maybe it's not serious enough.

**Comment by peppelinux** [comment]
as your command
https://github.com/IdentityPython/idpy-oidc/commit/60a69496f426ca5225bf00389e3205dca682b0a2

even if honestly everything oauth2 turns out decidedly ample and hardly coverable but ... the fortune helps the daring!

**Comment by rohe** [comment]
Aim for the moon and we may reach the tree tops.

**Comment by peppelinux** [comment]
I'll be there!

**Pull request merged**
