### PR TITLE
Support code_challenge_methods_supported

### PR DESCRIPTION
**Pull request by ctriant**
Add missing parameter `code_challenge_methods_supported` for PKCE

### CODE REVIEW

**Comment by rohe** [comment]
@ctriant please resolve conflicts and fix failing checks.

**Comment by ctriant** [comment]
> @ctriant please resolve conflicts and fix failing checks.

@rohe please have a look at this. Should I add the `code_challenge_methods_supported` on the client claims in the new fedservice approach?

**Comment by rohe** [comment]
Not sure I get what you mean with `client claims`.

**Comment by ctriant** [comment]
> Not sure I get what you mean with `client claims`.

This dict https://github.com/IdentityPython/idpy-oidc/blob/24519cc86f8c8223ede63c273e11014efd982a55/tests/test_08_transform.py#L44

**Comment by rohe** [comment]
`code_challenge_methods_supported` is part of Server Metadata according to RFC8414 but, in our case, should only appear IFF the add_on pkce is defined.  In the normal case with no add_on functionality it should not appear in the metadata.

test_08_transform.py doesn't deal with add_ons so `code_challenge_methods_supported` should not appear.

Just deal with the basic case right now. I'll tackle the add_ons.

**Comment by ctriant** [comment]
So, do you suggest any further changes?

**Review by rohe — APPROVED** [review]

**Pull request merged**
