### PR TITLE
Introduce userinfo policy

### PR DESCRIPTION
**Pull request by ctriant**
This PR adds the ability to configure a hook method on the userinfo endpoint configuration to apply policy on the generation of userinfo response.

### CODE REVIEW

**Comment by rohe** [comment]
@ctriant please resolve the conflicts.

**Review by rohe — COMMENTED** [review]
We already have class and function in the configuration. Do we really need a third - callable ??

**Comment by rohe** [comment]
I know `callable` already appears in a couple of places. I still think we have too many variants.

**Comment by ctriant** [comment]
this feature it's something we've discussed with @c00kiemon5ter and we decided to follow the same methodology as with token exchange and token revocation.

I don't mind if we refactor or even discard it. What's your opinion on that @c00kiemon5ter ?

**Comment by c00kiemon5ter** [comment]
What we need is a way to run a custom hook when the userinfo endpoint is invoked.

The immediate goal is to enrich the userinfo response with more data fetched by another remote URL, when a certain scope has been given to the access token.

The idea is to have this as an additional policy to the userinfo behaviour - the intention is not to modify the behaviour of the userinfo handler.

**Comment by rohe** [comment]
I have nothing against custom hooks. I just think that having basically two variants of hooks should be enough.
We now have `class` and `function` (beside `callable`). Using `class` allows you to specify additional key word arguments, used when initiating the class, through configuration. It also means that `class` most support the method __call__ .
`function` on the other hand is just a function that either takes known arguments or no arguments.
So what makes `callable` different to the extent that we can not use `function` or `class` in its place ?

**Pull request merged**
