### PR TITLE
Fedservice

### PR DESCRIPTION
**Pull request by rohe**
I tried to squash all the intermediate commits into one and it looked like it worked until I rebased fedservice unto develop.
I don't really understand why all the intermediates appear here but anyway the only thing you have to care about is the last commit.

What changed is the handling of configuration of entity preferences and who these plus for clients influences from OP provider info and possible dynamic client registration. All this is handled by the idpyoidc.Claims, idpyoidc.client.Claims and idpyoidc.server.Claims classes.

Another changes is that previously an entity was either a client (which could used services at service endpoints) or a server (provider of service endpoints). Now there is a class of entity that can be both at the same time. This is very useful in the context of OIDC Federation. A side effect of this was the need to be able to handle different key jars on different levels. To deal with this the method upstream_get was introduced. It allows a class/function/method to find the 'nearest' value of an attribute. 

More about the new functionality in the architectural documentation I'm working on.

### CODE REVIEW

**Comment by rohe** [comment]
Don't know why but the version that this PR is based on was not the latest I had.

**Comment by ctriant** [comment]
@rohe I can see token revocation documentation, but no related code or tests.

**Comment by rohe** [comment]
As I said the version I wanted was not the one I got. I'll go through the token revocation code.
I know I have it.

**Review by peppelinux — APPROVED** [review]
As said during our last meeting, I totally trust this important work made available in this PR, for tests and concrete revisions I'd prefer having it  merged on the develop branch and let the guys plying a while with it

thank you Roland!

**Pull request merged**
